# 2P
# pag.locateOnScreen("1.png", confidence=0.7)
# pointclick1 = (pag.locateOnScreen("Remove_2.png", confidence=0.7).left + 88, pag.locateOnScreen("Remove_2.png", confidence=0.7).top + 10)
# time.sleep(0.1)
# pag.click(pointclick1)
# time.sleep(0.1)
# DOM
# pag.locateOnScreen("2.png", confidence=0.5)
# time.sleep(0.1)
# pag.click("2.png")
# pointclick2 = (pag.locateOnScreen("Remove_2.png", confidence=0.7).left + 88, pag.locateOnScreen("Remove_2.png", confidence=0.7).top + 10)
# time.sleep(0.1)
# pag.click(pointclick2)
# time.sleep(0.1)
# pag.click(pointclick2)
# time.sleep(0.1)
# Before
# pag.locateOnScreen("3.png", confidence=0.5)
# time.sleep(0.1)
# pag.click("3.png")
# pointclick3 = (pag.locateOnScreen("Remove_2.png", confidence=0.7).left + 88, pag.locateOnScreen("Remove_2.png", confidence=0.7).top + 10)
# time.sleep(0.1)
# pag.click(pointclick3)
# time.sleep(0.1)
# Click
# pag.locateOnScreen("4.png", confidence=0.5)
# time.sleep(0.1)
# pag.click("4.png")
# pointclick4 = (pag.locateOnScreen("Remove_2.png", confidence=0.7).left + 88, pag.locateOnScreen("Remove_2.png", confidence=0.7).top + 10)
# time.sleep(0.1)
# pag.click(pointclick4)
# time.sleep(0.1)
# Load
# pag.locateOnScreen("6.png", confidence=0.5)
# time.sleep(0.1)
# pag.click("6.png")
# pointclick6 = (pag.locateOnScreen("Remove_2.png", confidence=0.7).left + 88, pag.locateOnScreen("Remove_2.png", confidence=0.7).top + 10)
# time.sleep(0.1)
# pag.click(pointclick6)
# time.sleep(0.1)
# pag.click(pointclick6)
# time.sleep(0.1)
# Locatech
# pag.locateOnScreen("7.png", confidence=0.5)
# time.sleep(0.1)
# pag.click("7.png")
# pointclick7 = (pag.locateOnScreen("Remove_2.png", confidence=0.7).left + 88, pag.locateOnScreen("Remove_2.png", confidence=0.7).top + 10)
# time.sleep(0.1)
# pag.click(pointclick7)
# time.sleep(0.1)
# Popstate
# pag.locateOnScreen("10.png", confidence=0.6)
# time.sleep(0.3)
# pag.click("10.png")
# pointclick10 = (pag.locateOnScreen("Remove_2.png", confidence=0.7).left + 88, pag.locateOnScreen("Remove_2.png", confidence=0.7).top + 10)
# time.sleep(0.1)
# pag.click(pointclick10)
# time.sleep(0.1)
# Message
# pag.locateOnScreen("8.png", confidence=0.6)
# time.sleep(0.3)
# pag.click("8.png")
# time.sleep(0.1)
# pointclick8 = (pag.locateOnScreen("Remove_2.png", confidence=0.7).left + 88, pag.locateOnScreen("Remove_2.png", confidence=0.7).top + 10)
# time.sleep(0.1)
# pag.click(pointclick8)
# time.sleep(0.1)
# Scroll
# pag.locateOnScreen("12.png", confidence=0.5)
# time.sleep(0.3)
# pag.click("12.png")
# pointclick12 = (pag.locateOnScreen("Remove_2.png", confidence=0.7).left + 88, pag.locateOnScreen("Remove_2.png", confidence=0.7).top + 10)
# time.sleep(0.1)
# pag.click(pointclick12)
# time.sleep(0.1)
# Visibilitychange